apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      restartPolicy: Always
      containers:
        - name: backend
          image: ritesh0419/task-backend:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:     # or configMapKeyRef if you're using ConfigMap
                  name: mongo-secret
                  key: MONGO_URI
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: task-backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#         - name: backend
#           image: ritesh0419/task-backend:latest
#           imagePullPolicy: Always
#           resources:
#             requests:
#               cpu: 100m
#               memory: 128Mi
#             limits:
#               cpu: 200m
#               memory: 256Mi
#           ports:
#             - containerPort: 5000
#           env:
#             - name: MONGO_URI
#               value: "mongodb+srv://ritesh:ritesh46@cluster0.llbotrp.mongodb.net/Todo?retryWrites=true&w=majority&appName=Cluster0"
#           livenessProbe:
#             httpGet:
#               path: /health
#               port: 5000
#             initialDelaySeconds: 10
#             periodSeconds: 10
#           readinessProbe:
#             httpGet:
#               path: /ready
#               port: 5000
#             initialDelaySeconds: 5
#             periodSeconds: 10
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: task-backend-service
# spec:
#   type: NodePort
#   selector:
#     app: backend
#   ports:
#     - port: 5000
#       targetPort: 5000
#       nodePort: 30001
