apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  ACCESS_TOKEN_SECRET: accessSuperSecret123
  REFRESH_TOKEN_SECRET: refreshUltraSecret123
  MONGODB_URI: mongodb+srv://ritesh:ritesh46@cluster0.llbotrp.mongodb.net/Taskprod?retryWrites=true&w=majority&appName=Cluster0
  OPEN_ROUTER_API_KEY: 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
