apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "5000"
  ACCESS_TOKEN_SECRET: accessSuperSecret123
  REFRESH_TOKEN_SECRET: refreshUltraSecret123
  OPEN_ROUTER_API_KEY: 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
