apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://ritesh:ritesh46@cluster0.llbotrp.mongodb.net/TaskProd?retryWrites=true&w=majority&appName=Cluster0
